### ISSUE TITLE
"ami-bada16ac" AMI image not found 

### ISSUE THREAD

**Issue by patrapatisunil** [awslabs/aws-serverless-auth-reference-app#19]
Not able to find EC2 instance "ami-bada16ac"

**Comment by justonian** [comment]
Hi patrapatisunil-

Did you try to launch this AMI from the us-east-1 region? We only offer the pre-built AMI there at this time, though it is simply a Docker Hub image that we published so you could pull it locally then deploy to the region of your choice if you'd like.

First, please try launching from us-east-1 and seeing if you encounter any other issues, though.

Thanks,

Justin

**Comment by patrapatisunil** [comment]
Hey,

Thanks, I will do that.

Regards,
Sunil

**Comment by patrapatisunil** [comment]
Thanks, Justin! I found the image and created an instance, but not able to
connect. I tried as both "root" and "ec2-user" but no luck.


"Disconnected: no supported authentication methods available (server sent
publickey)"

Appreciate if you could help me.

Regards,
Sunil Patrapati

**Comment by justonian** [comment]
Hi Sunil-

Did you set the appropriate SSH key when creating the EC2 instance? You'll need to have the private key locally on your machine (typically a .pem file) corresponding to the public key selected when connecting and use the -i parameter to point to the private key. The username for this AMI is ec2-user, but it will not allow password authentication and instead only work with the private key with certificate-based authentication.

Hope this helps.

Justin

**Comment by patrapatisunil** [comment]
hi Justin,

I figured out that we don't need an EC2 instance, so I fired up the gulp
command from my PC and got the setup up and running in minutes, the whole
setup experience was just cool. Thanks a ton!  I am exploring the IAM
based authorization.

Warm Regards,
Sunil Patrapati



Thanks and Regards,
*Sunil Patrapati *

* <http://www.redbangle.in>*
www.redbangle.in
