### ISSUE TITLE
 Property 'height' does not exist on type 'HTMLElement'

### ISSUE THREAD

**Issue by rohitvinay** [awslabs/aws-serverless-auth-reference-app#2]
When i try to emulate or build the application, I get the below error. 
```
Error: Error at /Users/user/Desktop/aws-serverless-auth-reference-app/app/.tmp/pages/account/account.ts:47:25
[04:30:24]  Property 'height' does not exist on type 'HTMLElement'. ```

**Comment by jtran21** [comment]
Hi Rohit, can you confirm that you are working with the latest version of the code? We had some users who also ran into this issue earlier, and the commit on Dec 16th should have addressed this.

**Comment by justonian** [comment]
Closing this issue as we believe the commit on December 16th should have resolved this. Please do a git pull to ensure you have the latest commit.

Please let us know if you're still encountering the issue afterwards. Thanks!
