### ISSUE TITLE
Unable to Find Public Community AMI - ami-bada16ac

### ISSUE THREAD

**Issue by tdevoe** [awslabs/aws-serverless-auth-reference-app#24]
Hopefully, this is the correct place to submit this question. I apologize in advance if it is not. I'm beginning to dive into AWS and Cognito and watched an AWS webcast that references this project. The link is https://www.youtube.com/watch?v=xLvZThZkWjI#t=1149.049 and the title of the webcast is "Add User Sign in and Management to your Apps with Amazon". You are asked to create an EC2 instance as shown below from an excerpt from the quickstart.md file included in this project. I cannot find the referenced Public Community AMI. Does anyone know if another exists that I can use? My experience is primarily Windows but will be working with AWS. The webcast was excellent and I'm excited to move forward with Cognito.

1. **Launch the EC2 instance** in your AWS account, using a public community AMI which contains a Docker image with a pre-configured SpaceFinder environment:

	- **Public Community AMI**: `ami-bada16ac`
	- **Instance type**: m4.large

Thanks,
Tom

**Comment by tdevoe** [comment]
I previously included the wrong link - it is was actually https://www.youtube.com/watch?v=n4hsWVXCuVI and it was titled: AWS reInvent MBL306 - Serverless Authentication and Authorization.

Thanks,
Tom

**Comment by ekkards** [comment]
The AMI is in us-east-1, the AMI ID is valid in only one region.

Searching by name "serverless" would find it also in other regions, if it existed.

**Comment by tdevoe** [comment]
Thank you! 

Tom

**Comment by justonian** [comment]
If you want to run this in a different region, simply pull and run the Docker image from https://hub.docker.com/r/awsdevops/aws-serverless-auth-reference-app/. The EC2 AMI is essentially just this image with Docker locally so it would be faster to download for people as the image is a few hundred MB. All you actually need is the Docker image, though.
