### ISSUE TITLE
Community AMI ami-bada16ac not found

### ISSUE THREAD

**Issue by deganmee** [awslabs/aws-serverless-auth-reference-app#25]
Would like to step through this quick start but I'm not able to find the AMI.

**Comment by ekkards** [comment]
see #24

**Comment by svenakela** [comment]
It doesn't exist in the EU region AFAIK. What you can do is, create the instance in US East, start it up, create an image and copy that image to your preferred region.
https://www.cloudberrylab.com/blog/how-to-move-amazon-ec2-to-different-availability-zone-vpc-region/

...or, just let the lab be in the US East region. :)

**Comment by justonian** [comment]
If you want to run this in a different region, simply pull and run the Docker image from https://hub.docker.com/r/awsdevops/aws-serverless-auth-reference-app/. The EC2 AMI is essentially just this image with Docker locally so it would be faster to download for people as the image is a few hundred MB. All you actually need is the Docker image, though.
