### ISSUE TITLE
Offline mode / Local development?

### ISSUE THREAD

**Issue by ejhayes** [awslabs/aws-serverless-auth-reference-app#26]
Is there any way to run this offline/locally? It looks like even the tests require the API to be deployed.

**Comment by justonian** [comment]
This project isn't meant for offline / local development, though you can create a separate entry point for testing and use local API emulation with Lambda. Alternatively, you can also use the open source Express project to run Express.js apps in a Lambda container then package up the entire thing as one or more Lambda functions then map API Gateway to it appropriately. This approach if fully testable locally, with the exception of any API Gateway mapping templates you use.

Let me know if you have further questions.
