### ISSUE TITLE
Gulp Deploy - ValidationError (create_cloudformation_stack)

### ISSUE THREAD

**Issue by F1LT3R** [awslabs/aws-serverless-auth-reference-app#28]
So far the steps in this Setup section of lab have worked without issue, but when running `gulp deploy` in Step 4,  I am bumping into something I have not been able to resolve. 

I am receiving the following error:

```
create_cloudformation_stack' errored after 279 ms
[17:41:15] ValidationError: Stack:arn:aws:cloudformation:us-east-1:123456789018:stack/spacefinder-api-development-stack/632a29c13zfe is in CREATE_FAILED state and can not be updated.
```

Things I have tried so far:

- Run through the steps a few times.
- Double checked the credentials are correct (key & secret in `aws configure`).
- Made sure the IAM user has admin privileges.

**Comment by justonian** [comment]
Hi F1LT3R- Can you try this again using the latest version of Node?

Did you hit this running int he Dockerized environment mentioned in the lab guide or when you tried to run the project on your own machine?

**Comment by justonian** [comment]
Closing this issue since I've not been able to re-produce it and others have not hit this issue.

**Comment by naheedmk** [comment]
I am also facing same issue , using Dockerized mentioned in the lab guide

**Comment by justonian** [comment]
This is likely a transient error which can happen seldomly with CloudFormation. To get around it, manually delete the stack from CloudFormation after first emptying any S3 buckets that CloudFormation created (it will fail deleting the stack if the buckets aren't first empty), then run "gulp deploy" again. Let me know if that doesn't fix it for you.

**Comment by naheedmk** [comment]
Thanks, it did fix the issue
