### ISSUE TITLE
Changing config.js to set region resulted in mixed-region deployment

### ISSUE THREAD

**Issue by Kirkaiya** [awslabs/aws-serverless-auth-reference-app#3]
First off, great job on this guys, a really useful sample.

When I did this last week, I edited the config.js to change AWS_REGION to us-west-2 (the optional step).  This resulted in the API Gateway stuff and Cognito user pools deploying to **us-west-2**, but the lambda functions and Dynamo tables all deployed to **us-east-1** (despite my local .aws/config file profile also having us-west-2).

It looks like data.js (in api/lambda/ folder) has the region hard-coded to _us-east-1_, which makes the Lambda and DynamoDB go there.  Should there be a step in the instructions to edit data.js (along with the optional step to change config.js) ?

**Comment by justonian** [comment]
Good catch, Kirk. I will look into this and aim to resolve in the next few days.

Thanks,

Justin

**Comment by ophilippsen** [comment]
Hi Justin, i prepared a pull request fixing the problem. 
As far i found a manual config overwrite was left in the dynamodb handler in you lambda functions. 
Removing it fixes the problem in my test environments.

**Comment by justonian** [comment]
Thanks, Oliver.

I merged your pull request and verified that Lambda now reads its region for DynamoDB connectivity from the container's environment variable, pointing to the correct region.

Thank you for contributing this pull request!
