### ISSUE TITLE
TypeError: AppScripts.serve is not a function

### ISSUE THREAD

**Issue by chadamodio** [awslabs/aws-serverless-auth-reference-app#32]
Receiving error "TypeError: AppScripts.serve is not a function" when running cmd ionic serve. 

To fix the error change app/package.json  line 37 @ionic/app-scripts: 1.0.0 to 1.1.4 then run npm install again.

**Comment by justonian** [comment]
I recently locked in the versions of Ionic and Bower as part of the project to maintain backwards compatibility. Going forward, I'm looking to resolve a few open issues with a pull request to upgrade the project to be fully compatible with the latest versions of Angular and Ionic. At that point, you should not have any issues running the project with the latest versions of these packages.

**Comment by UnicornFlames** [comment]
Hi There.

Try running this command. This might help you.

npm install --save-dev @latest

this will install the latest of app-scripts

**Comment by justonian** [comment]
This issue should now be fully fixed with the latest commits. Please try using the latest version of Ionic "npm install -g ionic" and the app should start fine with ionic serve. Let us know if you encounter any other issues. Thanks!
