### ISSUE TITLE
question

### ISSUE THREAD

**Issue by walshe** [awslabs/aws-serverless-auth-reference-app#34]
also looking at using serverless arch for a new app - had also been thinking of dynamodb like you , and since this was a booking app was just curious if the lack of ACID was a problem for you ?

**Comment by justonian** [comment]
With DynamoDB, you do have the option of optimistic locking, but need to have your code do conditional writes to check if the item is as you would expect and handle exception conditions. To also not need a lot of transactions (cross-table writes), it's important to create your UI in such a way that has certain steps only edit one item in one table at a time, then have future UIs do other related steps so you avoid cross-table transactions to start. Hope this helps clarify!
