### ISSUE TITLE
Side menu version

### ISSUE THREAD

**Issue by chadamodio** [awslabs/aws-serverless-auth-reference-app#36]
I am having trouble switching from the tab version to a side menu version. Has anyone created a side menu version and could post the code or instructions? Thanks in advance.

**Comment by justonian** [comment]
We don't have any active plans to make a side menu version at this time, but I would check out the https://github.com/ionic-team/ionic2-starter-aws project if you haven't already. Between using that as your starter project and the new Cognito hosted UI feature, you would not need a lot of the code that is built into this project and greatly simplify. Hope this helps!
