### ISSUE TITLE
Can not connect using putty and ec2-user

### ISSUE THREAD

**Issue by anothercoder2** [awslabs/aws-serverless-auth-reference-app#44]
hello,
I have converted my .pem key to .ppk. 
When trying to connect as ec2-user I get the error "Server refused our key"
Also tried root 
Thanks

**Comment by justonian** [comment]
Did you update the username that you're trying to connect with? Be sure to use "ec2-user" for any Amazon Linux-based AMI.

**Comment by anothercoder2** [comment]
I am using this guide. https://github.com/awslabs/aws-serverless-auth-reference-app/blob/master/Quickstart.md
I am using ec2-user and have been able to use it the past with other Amazon Linux APIs.
Thanks

**Comment by justonian** [comment]
Are you following the instructions at http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/AccessingInstancesLinux.html? This project has been around for almost one year and I've never had anyone have issues with this.

Also, when you created an instance from the public AMI we published in us-east-1, did you assign it the keypair that you're trying to connect with?

**Comment by justonian** [comment]
Alternatively, you can also pull the Docker image on the EC2 AMI locally if you're running the Docker engine on your computer from https://hub.docker.com/r/awsdevops/aws-serverless-auth-reference-app/. The only reason we had it on the EC2 instance is to not require all users of a previous workshop to download the Docker image locally, but it should be very quick assuming you have a reasonably fast internet connection.

**Comment by anothercoder2** [comment]
Yes the keypair is assigned .Launched with another account/keypair and it worked.  Not sure what the issue is with this account. Thanks for such prompt response.
Best

**Comment by justonian** [comment]
Good to hear. Closing this issue for now. Hope you find value in the app!
