### ISSUE TITLE
ReferenceError: awsSignWeb is not defined

### ISSUE THREAD

**Issue by rohitvinay** [awslabs/aws-serverless-auth-reference-app#6]
A reference error comes while loading bookings with `authClient`
`ReferenceError: awsSignWeb is not defined`

**Comment by justonian** [comment]
Hi Rohit-

When first cloning the project, you must be sure to run "bower install" in the /app directory to pull in the needed awsSignWeb library. This is a step in the readme that you probably skipped over accidentally.

Thanks,

Justin
