### ISSUE TITLE
POST error while booking a resource

### ISSUE THREAD

**Issue by rohitvinay** [awslabs/aws-serverless-auth-reference-app#8]
I am facing this error while booking a resouce
`POST https://5av9drf8dr.execute-api.us-east-1.amazonaws.com/development/users/us-east-1_10fvdgc6-d94c-4970-94bt-c3a94690tb1b/bookings 500 (Internal Server Error)`

**Comment by justonian** [comment]
Hi Rohit-

Thanks for reporting. We have a pending post request we're refining a bit that should resolve any intermittent 500 issues with the book resource Lambda function, as well as other improvements.

This should be merged in by the end of the week, so I will update this issue then once the changes are ready to be pulled.

Thanks,

Justin

**Comment by rohitvinay** [comment]
@justonian thank you, will watch for the update

**Comment by justonian** [comment]
Hi Rohit-

This issue is now resolved with the latest pull requests and changes. If you pull the latest commits to the project now, run npm install in all of the referenced places in the readme, and re-deploy, you should no longer have any issues with this.

Thanks for reporting the issue.

Justin
